Write lesson on debugging the user interaction program
learn-co-curriculum/java-debugger pull request #1
Opened 2023-02-01 20:54 UTC by kcleland0818

2023-02-01 21:36 UTC, linda-seiter reviewed
Before debugging a program that involves user input, can we step through debugging a program that has a logic error?  The way this lesson is written, it seems like the debugger is what you would use when dealing with exceptions.

2023-02-03 15:52 UTC, developerjaym commented on README.md
> +Let's say we had a pizza cutter where we could cut slice of pizza into thirds.
Consider adding 'a' between 'cut' and 'slice'

2023-02-03 15:53 UTC, developerjaym commented on src/main/java/BuggyProgram.java
> +        int slices = pizzaSlices / people;
Consider renaming 'slices' to 'slicesPerPerson'

2023-02-03 15:53 UTC, developerjaym approved these changes

2023-02-05 11:37 UTC, linda-seiter approved these changes
Nice lesson!

2023-02-08 04:25 UTC, kcleland0818 commented
I changed the variable `slices` to `slicesPerPerson` recommended by Jay. This involved changing some words and screenshots. Double check I caught them all please?

2023-02-08 20:52 UTC, developerjaym commented on README.md
> +    System.out.println("Each person should have " + slices + " slices of pizza.");
Should this be slicesPerPerson?

(Sorry!)

2023-02-08 20:53 UTC, developerjaym requested changes
Looks like one 'slices' didn't get updated

2023-02-09 17:56 UTC, developerjaym approved these changes

2023-02-10 17:51 UTC, linda-seiter approved these changes

2023-02-11 21:38 UTC, merged